### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by syedriko**
Port to Python3

### CODE REVIEW

**Comment by portante** [comment]
> /assign @portante

Would love to do this, but at this point in time I don't have the bandwidth.  I am certainly willing to help somebody ... ;)

**Comment by syedriko** [comment]
@portante I was hoping you'd hit the merge button :)

**Comment by portante** [comment]
Doh!  Thought this was an issue ... sec ...

**Comment by syedriko** [comment]
> Doh! Thought this was an issue ... sec ...

I'm not that audacious :)

**Pull request merged**
